
export default class DatabaseKeys {
    static counties = 
    // All counties in NC, Alphabetical Order
    [
        { key: 1, value: "alamance" },
        { key: 2, value: "alexander" },
        { key: 3, value: "alleghany" },
        { key: 4, value: "anson" },
        { key: 5, value: "ashe" },
        { key: 6, value: "avery" },
        { key: 7, value: "beaufort" },
        { key: 8, value: "beaufort" },
        { key: 9, value: "bertie" },
        { key: 10, value: "bladen" },
        { key: 11, value: "brunswick" },
        { key: 12, value: "buncombe" },
        { key: 13, value: "burke" },
        { key: 14, value: "cabarrus" },
        { key: 15, value: "caldwell" },
        { key: 16, value: "camden" },
        { key: 17, value: "carteret" },
        { key: 18, value: "caswell" },
        { key: 19, value: "catawba" },
        { key: 20, value: "chatham" },
        { key: 21, value: "cherokee" },
        { key: 22, value: "chowan" },
        { key: 23, value: "clay" },
        { key: 24, value: "cleveland" },
        { key: 25, value: "columbus" },
        { key: 26, value: "craven" },
        { key: 27, value: "cumberland" },
        { key: 28, value: "currituck" },
        { key: 29, value: "dare" },
        { key: 30, value: "davidson" },
        { key: 31, value: "davie" },
        { key: 32, value: "duplin" },
        { key: 33, value: "durham" },
        { key: 34, value: "edgecombe" },
        { key: 35, value: "forsyth" },
        { key: 36, value: "franklin" },
        { key: 37, value: "gaston" },
        { key: 38, value: "gates" },
        { key: 39, value: "graham" },
        { key: 40, value: "granville" },
        { key: 41, value: "greene" },
        { key: 42, value: "guilford" },
        { key: 43, value: "halifax" },
        { key: 44, value: "harnett" },
        { key: 45, value: "haywood" },
        { key: 46, value: "henderson" },
        { key: 47, value: "hertford" },
        { key: 48, value: "hoke" },
        { key: 49, value: "hyde" },
        { key: 50, value: "iredell" },
        { key: 51, value: "jackson" },
        { key: 52, value: "johnston" },
        { key: 53, value: "jones" },
        { key: 54, value: "lee" },
        { key: 55, value: "lenoir" },
        { key: 56, value: "lincoln" },
        { key: 57, value: "macon" },
        { key: 58, value: "madison" },
        { key: 59, value: "martin" },
        { key: 60, value: "mcdowell" },
        { key: 61, value: "mecklenburg" },
        { key: 62, value: "mitchell" },
        { key: 63, value: "montgomery" },
        { key: 64, value: "moore" },
        { key: 65, value: "nash" },
        { key: 66, value: "new hanover" },
        { key: 67, value: "northampton" },
        { key: 68, value: "onslow" },
        { key: 69, value: "orange" },
        { key: 70, value: "pamlico" },
        { key: 71, value: "pasquotank" },
        { key: 72, value: "pender" },
        { key: 73, value: "perquimans" },
        { key: 74, value: "person" },
        { key: 75, value: "pitt" },
        { key: 76, value: "polk" },
        { key: 77, value: "randolph" },
        { key: 78, value: "richmond" },
        { key: 79, value: "robeson" },
        { key: 80, value: "rockingham" },
        { key: 81, value: "rowan" },
        { key: 82, value: "sampson" },
        { key: 83, value: "scotland" },
        { key: 84, value: "stanly" },
        { key: 85, value: "stokes" },
        { key: 86, value: "surry" },
        { key: 87, value: "swain" },
        { key: 88, value: "transylvania" },
        { key: 89, value: "tyrrell" },
        { key: 90, value: "union" },
        { key: 91, value: "vance" },
        { key: 92, value: "wake" },
        { key: 93, value: "warren" },
        { key: 94, value: "washington" },
        { key: 95, value: "watauga" },
        { key: 96, value: "wayne" },
        { key: 97, value: "wilkes" },
        { key: 98, value: "wilson" },
        { key: 99, value: "yadkin" },
        { key: 100, value: "yancey" },
      ];      
    static categories = ["clothing", "bag", "electronic", "key", "wallet", "jewelry", "bottle", "book", "important documentation", "other"];
};

// Change Log: Added all NC counties: Karan 1/26/2024
// Change Log: Added some potential Categories of Items